name: collapsible_app_bar
description: A widget that has a collapsible app bar.
version: 0.1.2
repository: https://github.com/aJIEw/collapsible_app_bar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true